spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                # show_sql: true
                format_sql: true
        
mybatis:
    mapper-locations: mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true
    type-aliases-package: net.nonworkspace.demo
    
log4jdbc:
    spylogdelegator-name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
    dump:
        sql:
            maxlinelength: 0