spring:
    application:
        name: demo
    profiles:
        include: private, sql, swagger, jwt
        jdbc:
            initialize-schema: never
    data:
        web:
            pageable:
                default-page-size: 10
                one-indexed-parameters: true

logging.level:
        org.springframework: debug
        org.hibernate.SQL: debug
        org.hibernate.type: trace
        
batch:
    scheduling:
        enabled: false
    job:
        schedule: 0/15 * * * * ?