spring:
    application:
        name: demo
    profiles:
        include: private, sql, swagger, jwt
        jdbc:
            initialize-schema: never

logging.level:
        org.springframework: debug
        org.hibernate.SQL: debug
        org.hibernate.type: trace
        
batch:
    scheduling:
        enabled: false
    job:
        schedule: 0/30 * * * * ?