spring:
    jpa:
        hibernate:
            ddl-auto: none
            default_batch_fetch_size: 10
        properties:
            hibernate:
                show_sql: false #true
                format_sql: false #true
    datasource:
        p6spy:
            enable-logging: true
            multiline: true
            logging: slf4j
            tracing:
                include-parameter-values: true
        
mybatis:
    mapper-locations: mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: true
    type-aliases-package: net.nonworkspace.demo
    
log4jdbc:
    spylogdelegator-name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
    dump:
        sql:
            maxlinelength: 0