springdoc:
    package-to-scan: net.nonworkspace.demo.controller
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    api-docs:
        path: /api-docs
        groups:
            enabled: true
    swagger-ui:
        path: /swagger-ui.html
        disable-swagger-default-url: true
        display-request-duration: true
        groups-order: asc
        operations-sorter: method
    cache:
        disabled: true